# Generated by Django 5.2.3 on 2025-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranePhr', '0002_carousel_alter_images_photographer_images_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
