# Generated by Django 5.2.3 on 2025-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BranePhr', '0003_carousel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.RemoveField(
            model_name='images',
            name='photographer',
        ),
    ]
